"""LLM-as-a-judge for evaluating compression quality.

Given a compression event's context, asks a strong LLM whether the
compression lost critical information. Used as secondary signal
or validation for replay-based labels.

Usage:
    from memgym.training.augmentation.llm_judge import LLMJudge

    judge = LLMJudge(model="bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0")
    result = judge.judge_event(event)
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from typing import List, Optional

from memgym.training.data.compaction import CompactionEvent

logger = logging.getLogger(__name__)

JUDGE_PROMPT = """\
You are evaluating a memory compression event in a coding agent's conversation.

## Task Description
{problem_statement}

## Compression Event at Step {step}/{total_steps}
- Tokens before: {before_tokens}
- Tokens after: {after_tokens}
- Compression ratio: {ratio:.2f}x
- Messages forgotten: {forgotten}

## Summary Generated by Memory System
{summary}

## Agent's Next Action After Compression
{agent_action}

## Question
Did this compression lose critical information that the agent needs to solve the coding task?

Consider:
1. Were important file paths, function signatures, or error messages lost?
2. Were task requirements or pending investigation steps lost from the summary?
3. Did the agent's next action show confusion, repeat prior work, or miss something?

Respond with exactly one of:
- SAFE: Information was preserved adequately
- HARMFUL: Critical information was lost

Then explain in 1-2 sentences why."""


@dataclass
class JudgeResult:
    """Result from LLM judge evaluation."""

    instance_id: str
    step: int
    verdict: str  # "SAFE" or "HARMFUL"
    explanation: str
    label: int  # 1=SAFE, 0=HARMFUL
    raw_response: str = ""


class LLMJudge:
    """Ask a strong LLM whether a compression event lost critical information."""

    def __init__(
        self,
        model: str = "bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0",
        rate_limit_delay: float = 0.5,
        max_calls: int = 500,
    ):
        self.model = model
        self.rate_limit_delay = rate_limit_delay
        self.max_calls = max_calls
        self._calls = 0

    def judge_event(self, event: CompactionEvent) -> Optional[JudgeResult]:
        """Judge a single compaction event."""
        if self._calls >= self.max_calls:
            return None

        prompt = JUDGE_PROMPT.format(
            problem_statement=event.problem_statement[:2000],
            step=event.step,
            total_steps=event.total_steps,
            before_tokens=event.context_before_tokens,
            after_tokens=event.context_after_tokens,
            ratio=event.compression_ratio,
            forgotten=event.forgotten_count,
            summary=event.summary_generated[:3000],
            agent_action=event.agent_action[:1000],
        )

        try:
            import litellm

            response = litellm.completion(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=200,
                temperature=0.0,
            )
            self._calls += 1

            raw = response.choices[0].message.content or ""
            raw_upper = raw.strip().upper()

            if raw_upper.startswith("SAFE"):
                verdict = "SAFE"
                label = 1
            elif raw_upper.startswith("HARMFUL"):
                verdict = "HARMFUL"
                label = 0
            else:
                # Try to find verdict in response
                if "HARMFUL" in raw_upper:
                    verdict = "HARMFUL"
                    label = 0
                else:
                    verdict = "SAFE"
                    label = 1

            explanation = raw.strip()

            if self.rate_limit_delay > 0:
                time.sleep(self.rate_limit_delay)

            return JudgeResult(
                instance_id=event.instance_id,
                step=event.step,
                verdict=verdict,
                explanation=explanation,
                label=label,
                raw_response=raw,
            )

        except Exception as e:
            logger.warning("Judge call failed for %s step %d: %s",
                           event.instance_id, event.step, e)
            self._calls += 1
            return None

    def judge_batch(
        self,
        events: List[CompactionEvent],
        max_events: Optional[int] = None,
    ) -> List[JudgeResult]:
        """Judge multiple compaction events."""
        results = []
        to_judge = events[:max_events] if max_events else events

        for event in to_judge:
            if self._calls >= self.max_calls:
                logger.info("Judge call budget exhausted (%d)", self.max_calls)
                break

            result = self.judge_event(event)
            if result:
                results.append(result)

        return results
