"""LLM client and prompts for Coding-Synthetic pipeline v2."""

from .client import LLMClient, VerifierClient
from .prompts import (
    FACT_EXTRACTION_PROMPT,
    FACT_VERIFICATION_PROMPT,
    TASK_PROMPT_CRAFT_PROMPT,
    ADVERSARIAL_DISTRACTOR_PROMPT,
    MEMORY_FILE_ASSEMBLY_PROMPT,
    PROMPT_FUZZ_PROMPT,
    INDIRECTION_TRANSFORM_PROMPT,
    PATCH_GENERATION_SYSTEM,
    LLM_JUDGE_PROMPT,
)

__all__ = [
    "LLMClient",
    "VerifierClient",
    "FACT_EXTRACTION_PROMPT",
    "FACT_VERIFICATION_PROMPT",
    "TASK_PROMPT_CRAFT_PROMPT",
    "ADVERSARIAL_DISTRACTOR_PROMPT",
    "MEMORY_FILE_ASSEMBLY_PROMPT",
    "PROMPT_FUZZ_PROMPT",
    "INDIRECTION_TRANSFORM_PROMPT",
    "PATCH_GENERATION_SYSTEM",
    "LLM_JUDGE_PROMPT",
]
