"""LLM client and prompts for MemGym-IR v2 pipeline."""

from .client import LLMClient, VerifierClient
from .prompts import (
    PARAMETRIC_TEST_PROMPT,
    PARTIAL_CONTEXT_TEST_PROMPT,
    ANSWER_JUDGE_PROMPT,
    FACT_EXTRACTION_PROMPT,
    FACT_VERIFICATION_PROMPT,
    ADVERSARIAL_DISTRACTOR_PROMPT,
    SAME_ENTITY_CONTRADICTION_PROMPT,
    QUERY_FUZZ_PROMPT,
    ABLATION_QA_PROMPT,
)

__all__ = [
    "LLMClient",
    "VerifierClient",
    "PARAMETRIC_TEST_PROMPT",
    "PARTIAL_CONTEXT_TEST_PROMPT",
    "ANSWER_JUDGE_PROMPT",
    "FACT_EXTRACTION_PROMPT",
    "FACT_VERIFICATION_PROMPT",
    "ADVERSARIAL_DISTRACTOR_PROMPT",
    "SAME_ENTITY_CONTRADICTION_PROMPT",
    "QUERY_FUZZ_PROMPT",
    "ABLATION_QA_PROMPT",
]
